### PR TITLE
Edit about page copy and styling

### LINKED ISSUE #167: Some about page links are broken
A few of them seem to be using relative URLs when they should be absolute (link to contact email, old CourseRoad, FireRoad website).

### PR DESCRIPTION
**Pull request by wishdasher**
Didn't quite fix the logo, but edited the about page text and reordered things.

fixes #167

### CODE REVIEW

File: src/pages/About.vue [hunk 1]
```diff
@@ -1,77 +1,85 @@
...
-      <h2>Past maintainers</h2>
-      <p class = "px-5">
-        <ul style = "display: inline-block; text-align: left">
+      <h3 class="px-3">Past</h3>
+      <p class="px-3">
+        <ul style="display: inline-block;">
           <li>Danny Ben-David</li>
         </ul>
       </p>
-      <p class = "px-5">If you have questions or comments, please email <a href = "courseroad-dev.mit.edu">us</a>.</p>
```
Comment (wishdasher) [inline src/pages/About.vue]: Assuming this was a typo?

File: src/pages/About.vue [hunk 2]
```diff
@@ -1,77 +1,85 @@
 <template>
   <v-container>
-    <router-link to = "/" style = "color: inherit; text-decoration: none;">
+    <router-link to="/" style="color: inherit; text-decoration: none;">
       <v-btn icon flat>
         <v-icon>arrow_back</v-icon>
       </v-btn>
     </router-link>
-    <div class = "text-sm-center pa-2">
```
Comment (wishdasher) [inline src/pages/About.vue]: Uncentered text for easier readability
